---
version: "3.8"
services:
  movies:
    image: prat1402/movies:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  train:
    image: prat1402/train:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: prat1402/dth:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
  recharge:
    image: prat1402/recharge:latest
    ports:
      - 85:80
    deploy:
      replicas: 3
